<?php
include "php/database.php";
const CONNEXION = 'mysql:host=localhost;dbname=blog';
const USER_ID = 'root';
const PASSWORD = 'troiswa';
$db = connect(CONNEXION,USER_ID,PASSWORD);
$db->exec("SET NAME UTF8");
include "php/frontController.php";
$tab = displayCategorie($db);
// var_dump($tab);
// die;
?>
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="description" content="">
        <title>Document</title>
        <!--<script defer src="index.js"></script>-->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css"><!---->
        <link rel="stylesheet" href="css/normalize.css" />
        <link rel="stylesheet" href="css/style.css" />
</head>
<body>
    <header>
        <!-- <div class="container">
            <a href="#"><img src="img/logo.svg" alt="logo">John Doe</a>
            <nav>
                <a href="index.html">location</a>
                <a href="#">about us</a>
                <a href="#">contact</a>
            </nav>
        </div> -->
    </header>
    <main id="index">
        <section class="marge">
        <h1></h1>
        <div class="container">
            <?php
            include "templates/categoryForm.phtml";
            include "templates/userForm.phtml";
            ?>
        </div>
        </section>
    </main>
    <footer>
        <p>
            <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/">
                <img alt="Propriété de la 3W Academy" src="img/big.png" />
            </a><br />
                
            <span>Cet exercice</span> de <a href="https://3wa.fr">3W Academy</a> est mis à disposition <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/">pour l'usage personnel des étudiants, Pas de Rediffusion - Attribution - Pas d'Utilisation Commerciale - Pas de Modification - International</a>.<br />
                
            Les autorisations au-delà du champ de cette licence peuvent être obtenues auprès de <a href="mailto:contact@3wa.fr" rel="cc:morePermissions">contact@3wa.fr</a>. Les maquettes ont été réalisées par <a href="http://www.justine-muller.fr">Justine Muller</a>.
        </p>
    </footer>
</body>
</html>