
<h1>Catégorie</h1>
<form action="" method="post" class="form-exemple">
<label for="titre"> titre </label>
<input type="text" name="titre" id="titre"required>
<label for="description ">description</label>
<textarea name="description" id="description" cols="30" rows="10"></textarea>
<select name="parent"   id="parent">
       <option value="">sans parent</option>
       <?php
       foreach ($tab as $cat):
       ?>
       <option value="<?=$cat["id"] ?>"><?= $cat["titre"]?></option>
       <?php 
       endforeach
       ?>
<input type="hidden" name="case" value = "create-category">
<input type="submit" name="submit" value ="créer une catégorie">
</form>



<?php

?>