<h1>Utilisateur</h1>
<form action="" method="post" class="form-exemple">
<label for="email"> email </label>
<input type="email" name="email" id="email" required>

<label for="prenom">prenom</label>
<input type="text" name="prenom" id="prenom">

<label for="nom">nom</label>
<input type="text" name="nom" id="nom">

<label for="mot_de_passe">mot de passe</label>
<input type="text" name="mot_de_passe" id="mot_de_passe">
<select name="role"   id="role">
       <option value="superadmin">super administrateur</option>
       <option value="admin">administrateur</option>
       <option value="auteur">auteur</option>
       <option value="abonné">abonné</option>
       <option value="lecteur">lecteur</option>


<input type="hidden" name="case" value = "create-user">
<input type="submit" name="submit" value ="enregistrer">
</form>



<?php

?>